
[English]
Continue = 'Continue'
Go_Back = 'Go Back'
Choreo = 'Choreo'
Ready_Dance = 'Ready to Dance!'
Sort_Title = '''SORT BY
TITLE'''
Sort_Artist = '''SORT BY
ARTIST'''
Sort_Level = '''SORT BY
LEVEL'''
Level = 'LEVEL'
Sort_Score = '''SORT BY
HIGH SCORE'''
DJ_choice = 'DJ’S CHOICE'
Easy = 'Easy'
Normal = 'Normal'
Hard = 'Hard'
Scroll = 'Scroll'
Auto_Mode_Enabled = '''AUTOMODE ENABLED'''
Stylish = 'STYLISH'
Cool = 'COOL'
Good = 'GOOD'
Miss = 'MISS'
Early = 'Early'
Late = 'Late'
Results = 'RESULTS'
Accuracy = 'ACCURACY'
Full_Combo = 'Full Combo'
Cleared = 'Cleared'
Failed = 'Failed'
Forfeit = 'Forfeit'
No_Songs_Title = 'NO SONGS LOADED'
No_Songs_Desc = 'Add song files to the folder “StyleStar/Songs”. Each song should be in its own subfolder, and contain the audio file, the song metadata (.ssi), and one or more chart files (.ssf).'
Lang_Title = 'LANGUAGE'
Lang_Open = 'Open language select...'
Lang_Name = 'English'
Screen_Res = 'SCREEN RESOLUTION'
Touch_Res = 'TOUCH SCREEN ORIENTATION'
Hor_0 = 'Horizontal (0°)'
Ver_90 = 'Vertical (90°)'
Hor_180 = 'Horizontal (180°)'
Ver_270 = 'Vertical (270°)'
En_Free = 'ENABLE FREE PLAY'
Auto_Mode_2 = 'AUTO MODE'
On = 'ON'
Off = 'OFF'
Down_Only = 'DOWN ONLY'
Save_Exit = 'Save and Exit'
Leave_No_Save = 'Leave without Saving'
Select_Confirm = 'Press SELECT again to confirm changes.'
Select_Discard = 'Press SELECT again to discard changes.'

[Spanish]
Continue = 'Continuar'
Go_Back = 'Retroceder'
Choreo = 'Coreografía'
Ready_Dance = '¡Vamos a bailar!'
Sort_Title = 'ORDENAR POR TÍTULO'
Sort_Artist = 'ORDENAR POR ARTISTA'
Sort_Level = 'ORDENAR POR NIVEL'
Level = 'NIVEL'
Sort_Score = 'ORDENAR POR HIGHSCORE'
DJ_choice = 'DEJA QUE EL DJ DECIDIR'
Easy = 'Fácil'
Normal = 'Regular'
Hard = 'Difícil'
Scroll = 'Velocidad'
Auto_Mode_Enabled = 'Modo Auto Activado'
Stylish = 'ESTILOSO'
Cool = 'GUAY'
Good = 'BIEN'
Miss = 'FALLO'
Early = 'Pronto'
Late = 'Tarde'
Results = 'RESULTADOS'
Accuracy = 'Precisión'
Full_Combo = 'Combo Completo'
Cleared = 'Pasado'
Failed = 'Fallido'
Forfeit = 'Abandonado'
No_Songs_Title = 'NO HAY CANCIONES'
No_Songs_Desc = 'Añada archivos a la carpeta "StyleStar/Songs". Cada canción debe tener su propia carpeta, y contener un archivo de audio, los metadatos (.ssi) y al menos un archivo para la partitura (.ssf).'
Lang_Title = 'Language'
Lang_Open = 'Open language select...'
Lang_Name = 'Español'
Screen_Res = 'Screen resolution'
Touch_Res = 'Touchscreen orientation'
Hor_0 = 'Horizontal (0°)'
Ver_90 = 'Vertical (90°)'
Hor_180 = 'Horizontal (180°)'
Ver_270 = 'Vertical (270°)'
En_Free = 'Enable Free Play'
Auto_Mode_2 = 'Auto mode'
On = 'On'
Off = 'Off'
Down_Only = 'DOWN only'
Save_Exit = 'Save and Exit'
Leave_No_Save = 'Leave without Saving'
Select_Confirm = 'Press SELECT again to confirm changes.'
Select_Discard = 'Press SELECT again to discard changes.'

[Japanese]
Continue = '次へ'
Go_Back = '戻る'
Choreo = '振付'
Ready_Dance = '準備オッケー'
Sort_Title = 'タイトルで並べ替え'
Sort_Artist = 'アーティストで並べ替え'
Sort_Level = 'レベルで並べ替え'
Level = 'レベル'
Sort_Score = 'ハイスコアで並べ替え'
DJ_choice = 'DJにお任せ'
Easy = '簡単'
Normal = '普通'
Hard = '難しい'
Scroll = 'スクロール'
Auto_Mode_Enabled = 'オートプレイON'
Stylish = 'スタイリッシュ'
Cool = 'イケテル'
Good = 'ウマイ'
Miss = 'ミス'
Early = '早すぎ'
Late = '遅すぎ'
Results = 'ケッカ ハッピョウ'
Accuracy = '精度'
Full_Combo = 'フルコンボ'
Cleared = 'クリア'
Failed = 'クリアならず'
Forfeit = 'ギブアップ'
No_Songs_Title = 'ガッキョクデータガアリマセン'
No_Songs_Desc = '曲のファイルをフォルダ StyleStar¥Songs に、一曲づつサブフォルダに入れてください。一曲につき、音声ファイル1個と、楽曲メタデータファイル（.ssi）1個と、譜面ファイル（.ssf）1個以上が必要です。'
Lang_Title = '言語'
Lang_Open = '言語選択を開く...'
Lang_Name = '日本語'
Screen_Res = '画面解像度'
Touch_Res = 'タッチスクリーンの向き'
Hor_0 = '横 (0°)'
Ver_90 = '縦 (90°)'
Hor_180 = '横 (180°)'
Ver_270 = '縦 (270°)'
En_Free = 'フリープレイをオンにする'
Auto_Mode_2 = 'オートプレイ'
On = '有効'
Off = '無効'
Down_Only = 'DOWNのみ'
Save_Exit = '保存して終了'
Leave_No_Save = '保存せずに終了'
Select_Confirm = '変更を保存するには、SELECTを押してください。'
Select_Discard = '変更を破棄するには、SELECTを押してください。'

[French]
Continue = 'Continuer'
Go_Back = 'Retour'
Choreo = 'Chorégraphie'
Ready_Dance = 'Prêt à danser!'
Sort_Title = 'TRIER PAR TITRE'
Sort_Artist = 'TRIER PAR ARTISTE'
Sort_Level = 'TRIER PAR NIVEAU'
Level = 'NIVEAU'
Sort_Score = 'TRIER PAR SCORE'
DJ_choice = 'CHOIX DU DJ'
Easy = 'Facile'
Normal = 'Normal'
Hard = 'Difficile'
Scroll = 'Défilement'
Auto_Mode_Enabled = 'Mode automatique'
Stylish = 'STYLÉ'
Cool = 'COOL'
Good = 'BIEN'
Miss = 'RATÉ'
Early = 'Trop tôt'
Late = 'Trop tard'
Results = 'RÉSULTATS'
Accuracy = 'Précision'
Full_Combo = 'Combo parfait'
Cleared = 'Réussi'
Failed = 'Échec'
Forfeit = 'Abandon'
No_Songs_Title = 'AUCUNE CHANSON TROUVÉE'
No_Songs_Desc = 'Ajoute des fichiers de chansons dans le dossier "StyleStar/Songs". Chaque chanson doit se trouver dans son propre dossier, et doit contenir le fichier audio, les métadonnées (.ssi), et une ou plusieurs chorégraphies (.ssf).'
Lang_Title = 'Langue'
Lang_Open = 'Ouvre la sélection de langue...'
Lang_Name = 'Français'
Screen_Res = "Résolution d'écran"
Touch_Res = "Orientation de l'écran"
Hor_0 = 'Paysage (0°)'
Ver_90 = 'Portrait (90°)'
Hor_180 = 'Paysage inversé (180°)'
Ver_270 = 'Portrait inversé (270°)'
En_Free = 'Activer le Free Play'
Auto_Mode_2 = 'Mode automatique'
On = 'Activé'
Off = 'Désactivé'
Down_Only = 'Seulement vers le bas'
Save_Exit = 'Enregistrer et quitter'
Leave_No_Save = 'Quitter sans enregistrer'
Select_Confirm = 'Appuyez sur SELECT à nouveau pour confirmer les changements'
Select_Discard = 'Appuyer sur SELECT à nouveau pour ignorer les changements'